export { default as salad } from "./salad1.png"
export { default as Cheese } from "./c1.png"
export { default as Bacon } from "./bc1.png"
export { default as Meat } from "./m1.png"
export { default as leave } from "./l1.png"

export { default as tamato } from "./t1.png"
export { default as noData } from "../NodataVa.svg"
export { default as UnderConstruction } from "../UnderConstructionVa.svg"
export { default as EmptyCart } from "../EmptyCartVa.svg"
export { default as Contactus } from "../contactusVa.svg"